name = "FPLLL"
uuid = "03c0f9b8-8f98-4d15-83bb-8707f2d8d9c2"
version = "0.2.0"
authors = ["FPLLL.jl contributors"]

[deps]
FPLLL_jll = "a3a2a55f-686a-5b05-901e-e415bf757ff5"

[sources]
FPLLL_jll = {url = "https://github.com/wbhart/FPLLL_jll.jl.git"}

[compat]
julia = "1.9"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Random", "Test"]
